import defaultTheme from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './safelist.txt',
    './app/pages/**/*.vue',
    './app/components/ch/**/*.vue',
    './app/components/stories/layout/*.stories.mdx',
  ],
  corePlugins: {
    container: false,
  },
  theme: {
    extend: {
      animation: {
        'spin-fast': 'spin 0.5s linear infinite',
      },
    },
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1544px',
      '3xl': '1920px',
    },
    container: {
      '2xl': '1544px',
      '3xl': '1676px',
    },
    scale: {
      102: '1.02',
      ...defaultTheme.scale,
    },
    colors: {
      current: 'currentColor',
      inherit: 'inherit',

      // Legacy
      white: '#ffffff',
      black: '#000000',
      transparent: 'transparent',

      // New color primitives
      'standard-black': 'var(--standard-black)',
      'standard-transparent': 'var(--standard-transparent)',
      'standard-white': 'var(--standard-white)',
      primary: {
        50: 'var(--color-primary-50)',
        100: 'var(--color-primary-100)',
        200: 'var(--color-primary-200)',
        300: 'var(--color-primary-300)',
        400: 'var(--color-primary-400)',
        500: 'var(--color-primary-500)',
        600: 'var(--color-primary-600)',
        700: 'var(--color-primary-700)',
        800: 'var(--color-primary-800)',
        900: 'var(--color-primary-900)',
      },
      secondary: {
        50: 'var(--color-secondary-50)',
        100: 'var(--color-secondary-100)',
        200: 'var(--color-secondary-200)',
        300: 'var(--color-secondary-300)',
        400: 'var(--color-secondary-400)',
        500: 'var(--color-secondary-500)',
        600: 'var(--color-secondary-600)',
        700: 'var(--color-secondary-700)',
        800: 'var(--color-secondary-800)',
        900: 'var(--color-secondary-900)',
      },
      text: {
        50: 'var(--text-50)',
        100: 'var(--text-100)',
        200: 'var(--text-200)',
        300: 'var(--text-300)',
        400: 'var(--text-400)',
        500: 'var(--text-500)',
        600: 'var(--text-600)',
        700: 'var(--text-700)',
        800: 'var(--text-800)',
        900: '#111827', // 'var(--text-900)',
      },
      blue: {
        50: 'var(--blue-50)',
        100: 'var(--blue-100)',
        200: 'var(--blue-200)',
        300: 'var(--blue-300)',
        400: 'var(--blue-400)',
        500: 'var(--blue-500)',
        600: 'var(--blue-600)',
        700: 'var(--blue-700)',
        800: 'var(--blue-800)',
        900: 'var(--blue-900)',
      },
      gray: {
        50: 'var(--gray-50)',
        100: 'var(--gray-100)',
        200: 'var(--gray-200)',
        300: 'var(--gray-300)',
        400: 'var(--gray-400)',
        500: 'var(--gray-500)',
        600: 'var(--gray-600)',
        700: 'var(--gray-700)',
        800: 'var(--gray-800)',
        900: 'var(--gray-900)',
      },
      green: {
        50: 'var(--green-50)',
        100: 'var(--green-100)',
        200: 'var(--green-200)',
        300: 'var(--green-300)',
        400: 'var(--green-400)',
        500: 'var(--green-500)',
        600: 'var(--green-600)',
        700: 'var(--green-700)',
        800: 'var(--green-800)',
        900: 'var(--green-900)',
      },
      indigo: {
        50: 'var(--indigo-50)',
        100: 'var(--indigo-100)',
        200: 'var(--indigo-200)',
        300: 'var(--indigo-300)',
        400: 'var(--indigo-400)',
        500: 'var(--indigo-500)',
        600: 'var(--indigo-600)',
        700: 'var(--indigo-700)',
        800: 'var(--indigo-800)',
        900: 'var(--indigo-900)',
      },
      orange: {
        50: 'var(--orange-50)',
        100: 'var(--orange-100)',
        200: 'var(--orange-200)',
        300: 'var(--orange-300)',
        400: 'var(--orange-400)',
        500: 'var(--orange-500)',
        600: 'var(--orange-600)',
        700: 'var(--orange-700)',
        800: 'var(--orange-800)',
        900: 'var(--orange-900)',
      },
      pink: {
        50: 'var(--pink-50)',
        100: 'var(--pink-100)',
        200: 'var(--pink-200)',
        300: 'var(--pink-300)',
        400: 'var(--pink-400)',
        500: 'var(--pink-500)',
        600: 'var(--pink-600)',
        700: 'var(--pink-700)',
        800: 'var(--pink-800)',
        900: 'var(--pink-900)',
      },
      purple: {
        50: 'var(--purple-50)',
        100: 'var(--purple-100)',
        200: 'var(--purple-200)',
        300: 'var(--purple-300)',
        400: 'var(--purple-400)',
        500: 'var(--purple-500)',
        600: 'var(--purple-600)',
        700: 'var(--purple-700)',
        800: 'var(--purple-800)',
        900: 'var(--purple-900)',
      },
      red: {
        50: 'var(--red-50)',
        100: 'var(--red-100)',
        200: 'var(--red-200)',
        300: 'var(--red-300)',
        400: 'var(--red-400)',
        500: 'var(--red-500)',
        600: 'var(--red-600)',
        700: 'var(--red-700)',
        800: 'var(--red-800)',
        900: 'var(--red-900)',
      },
      teal: {
        50: 'var(--teal-50)',
        100: 'var(--teal-100)',
        200: 'var(--teal-200)',
        300: 'var(--teal-300)',
        400: 'var(--teal-400)',
        500: 'var(--teal-500)',
        600: 'var(--teal-600)',
        700: 'var(--teal-700)',
        800: 'var(--teal-800)',
        900: 'var(--teal-900)',
      },
      yellow: {
        50: 'var(--yellow-50)',
        100: 'var(--yellow-100)',
        200: 'var(--yellow-200)',
        300: 'var(--yellow-300)',
        400: 'var(--yellow-400)',
        500: 'var(--yellow-500)',
        600: 'var(--yellow-600)',
        700: 'var(--yellow-700)',
        800: 'var(--yellow-800)',
        900: 'var(--yellow-900)',
      },

      // New color tokens
      action: {
        'background-cta-default': 'var(--action-background-cta-default)',
        'background-cta-disabled': 'var(--action-background-cta-disabled)',
        'darkmode-hover-red': 'var(--primary-700)',
        'darkmode-main-red': 'var(--primary-600)',
        disabled: 'var(--action-disabled)',
        focus: 'var(--action-focus)',
        'hover-main': 'var(--action-hover-main)',
        'hover-secondary': 'var(--action-hover-secondary)',
        main: 'var(--action-main)',
        secondary: 'var(--action-secondary)',
      },
      background: {
        'accent-01': 'var(--background-accent-01)',
        'accent-02': 'var(--background-accent-02)',
        'background-modal': 'var(--background-background-modal)',
        main: 'var(--background-main)',
      },
      elements: {
        color: '#ffffff',
        'card-01': 'var(--elements-card-card-01)',
        'card-hover': 'var(--elements-card-hover)',
        'card-shadow': 'var(--elements-card-shadow)',
        'divider-50': 'var(--elements-divider-50)',
        'divider-100': 'var(--elements-divider-100)',
        'divider-200': 'var(--elements-divider-200)',
        'support-50': 'var(--elements-support-50)',
        'support-100': 'var(--elements-support-100)',
        'support-200': 'var(--elements-support-200)',
        'support-300': 'var(--elements-support-300)',
        'support-400': 'var(--elements-support-400)',
        'support-500': 'var(--elements-support-500)',
        'support-600': 'var(--elements-support-600)',
        'support-700': 'var(--elements-support-700)',
        'support-800': 'var(--elements-support-800)',
        'support-900': 'var(--elements-support-900)',
      },
      gebaerdensprache: {
        accent: 'var(--gebaerdensprache-accent)',
        main: 'var(--gebaerdensprache-main)',
        text: 'var(--gebaerdensprache-text)',
      },
      leichtesprache: {
        accent: 'var(--leichtesprache-accent)',
        main: 'var(--leichtesprache-main)',
        text: 'var(--leichtesprache-text)',
      },
      logo: {
        'logo-red': 'var(--logo-logo-red)',
        'logo-white': 'var(--logo-logo-white)',
      },
      states: {
        'error-bg': 'var(--states-error-error-bg)',
        'error-text': 'var(--states-error-error-text)',
        'information-bg': 'var(--states-information-information-bg)',
        'information-text': 'var(--states-information-information-text)',
        'neutral-bg': 'var(--states-neutral-neutral-bg)',
        'neutral-text': 'var(--states-neutral-neutral-text)',
        'success-bg': 'var(--states-success-success-bg)',
        'success-text': 'var(--states-success-success-text)',
        'warning-bg': 'var(--states-warning-warning-bg)',
        'warning-text': 'var(--states-warning-warning-text)',
      },
      'text-new': {
        contrast: 'var(--text-contrast-text)',
        disabled: 'var(--text-disabled-text)',
        label: 'var(--text-label-text)',
        main: 'var(--text-main-text)',
        quote: 'var(--text-quote-text)',
        selected: 'var(--text-selected-text)',
      },
      'ui-elements': {
        checkbox: {
          'active-background': 'var(--ui-elements-checkbox-active-background)',
          checkmark: 'var(--ui-elements-checkbox-checkmark)',
          'disabled-background':
            'var(--ui-elements-checkbox-disabled-background)',
          'disabled-stroke': 'var(--ui-elements-checkbox-disabled-stroke)',
          'disabled-text': 'var(--ui-elements-checkbox-disabled-text)',
          'inactive-background':
            'var(--ui-elements-checkbox-inactive-background)',
          'main-stroke': 'var(--ui-elements-checkbox-main-stroke)',
          'main-text': 'var(--ui-elements-checkbox-main-text)',
        },
        close: {
          background: 'var(--ui-elements-close-background)',
          item: 'var(--ui-elements-close-item)',
        },
        indicator: {
          active: 'var(--ui-elements-indicator-indicator-active)',
          inactive: 'var(--ui-elements-indicator-indicator-inactive)',
        },
        inputfield: {
          select: {
            'disabled-background':
              'var(--ui-elements-inputfield-select-background-disabled-background)',
            'main-background':
              'var(--ui-elements-inputfield-select-background-main-background)',
            'active-indicator':
              'var(--ui-elements-inputfield-select-indicator-active-indicator)',
            'disabled-indicator':
              'var(--ui-elements-inputfield-select-indicator-disabled-indicator)',
            'disabled-stroke':
              'var(--ui-elements-inputfield-select-stroke-disabled-stroke)',
            'error-stroke':
              'var(--ui-elements-inputfield-select-stroke-error-stroke)',
            'main-stroke':
              'var(--ui-elements-inputfield-select-stroke-main-stroke)',
            'disabled-text':
              'var(--ui-elements-inputfield-select-text-disabled-text)',
            'error-text':
              'var(--ui-elements-inputfield-select-text-error-text)',
            'label-text':
              'var(--ui-elements-inputfield-select-text-label-text)',
            'main-text': 'var(--ui-elements-inputfield-select-text-main-text)',
          },
        },
        navigation: {
          '01': 'var(--ui-elements-navigation-01)',
          '02': 'var(--ui-elements-navigation-02)',
          '03': 'var(--ui-elements-navigation-03)',
        },
        radiobutton: {
          'active-background':
            'var(--ui-elements-radiobutton-active-background)',
          checkmark: 'var(--ui-elements-radiobutton-checkmark)',
          'disabled-background':
            'var(--ui-elements-radiobutton-disabled-background)',
          'disabled-stroke': 'var(--ui-elements-radiobutton-disabled-stroke)',
          'disabled-text': 'var(--ui-elements-radiobutton-disabled-text)',
          'inactive-background':
            'var(--ui-elements-radiobutton-inactive-background)',
          'main-stroke': 'var(--ui-elements-radiobutton-main-stroke)',
          'main-text': 'var(--ui-elements-radiobutton-main-text)',
        },
        tag: {
          'background-active': 'var(--ui-elements-tag-background-active)',
          'background-default': 'var(--ui-elements-tag-background-default)',
          'background-disabled-fill':
            'var(--ui-elements-tag-background-disabled-fill)',
          'background-disabled-stroke':
            'var(--ui-elements-tag-background-disabled-stroke)',
          'background-hover': 'var(--ui-elements-tag-background-hover)',
        },
        toggle: {
          'active-background': 'var(--ui-elements-toggle-active-background)',
          checkmark: 'var(--ui-elements-toggle-checkmark)',
          'inactive-background-2':
            'var(--ui-elements-toggle-inactive-background-2)',
        },
      },
    },
    fontWeight: {
      normal: 400,
      bold: 400,
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.375rem',
      '3xl': '1.625rem',
      '4xl': '2rem',
      '5xl': '2.5rem',
      '6xl': '3rem',
      '7xl': '3.5rem',
      '8xl': '4rem',
      '9xl': '5rem',
    },
    fontFamily: {
      regular: ['Font-Regular', 'Hind', 'Fallback-font', 'Sans-Serif'],
      italic: ['Font-Italic', 'Hind', 'Fallback-font'],
      bold: ['Font-Bold', 'Hind', 'Fallback-font'],
      'bold-italic': ['Font-Bold-Italic', 'Hind', 'Fallback-font'],
    },
    boxShadow: {
      // TODO: add dark mode support to 0,0,0 shadows
      sm: '0 1px 2px 0 rgba(0,0,0,0.05)',
      DEFAULT: '0 1px 2px 0 rgba(0,0,0,0.06), 0 1px 5px 0 rgba(0,0,0,0.08)',
      md: '0 2px 4px -1px rgba(0,0,0,0.06), 0 4px 10px -1px rgba(0,0,0,0.08)',
      lg: '0 2px 6px -1px rgba(0,0,0,0.06), 0 5px 20px -3px rgba(0,0,0,0.08)',
      xl: '0 6px 10px -5px rgba(0,0,0,0.06), 0 15px 25px -3px rgba(0,0,0,0.09)',
      '2xl':
        '0 10px 20px 0 rgba(0,0,0,0.06), 1px 10px 70px -8px rgba(0,0,0,0.13)',
      none: '0 0 0 0 rgba(0,0,0,0)',
      focus: '0 0 0 3px var(--purple-500)',
    },
    borderRadius: {
      none: '0',
      xs: '0.0625rem',
      sm: '0.125rem',
      DEFAULT: '0.1875rem',
      lg: '0.3125rem',
      xl: '0.375rem',
      '2xl': '0.5rem',
      '3xl': '0.625rem',
      '4xl': '0.75rem',
      '5xl': '0.9375rem',
      '6xl': '1.5rem',
      full: '9999px',
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
      square: 'square',
      roman: 'upper-roman',
    },
  },
  variants: {
    extend: {},
  },
}
